# Dataset pattern for selecting directories
dataset_pattern: "0dB/fan/*"

dataset:
  db_levels: ["0dB", "6dB", "min6dB"]
  machine_types: ["fan", "pump", "slider", "valve"]

# Feature extraction parameters
feature:
  n_mels: 64
  frames: 5
  n_fft: 1024
  hop_length: 512
  power: 2.0
  ssim_window_size: 3

# Transformer model parameters
transformer:
  head_size: 64
  num_heads: 4
  ff_dim: 128
  num_transformer_blocks: 2
  mlp_units: [128, 64]
  dropout: 0.2

# Fit algorithm parameters
fit:
  compile:
    optimizer: "adam"
    loss: "ssim_loss"
  learning_rate: 0.001
  epochs: 100
  batch_size: 512
  prediction_batch_size: 128
  shuffle: True
  validation_split: 0.1
  verbose: 1
  early_stopping: True
  max_spectrograms_to_store: 20
  max_samples_per_spectrogram: 10

# Directory paths
base_directory: "./dataset"
pickle_directory: "./pickle"
model_directory: "./model"
result_directory: "./result"
result_file: "result.yaml"