# General parameters
version: "3.0.0"

# Feature extraction parameters
feature:
  n_mels: 128
  frames: 5
  n_fft: 1024
  hop_length: 512
  stride: 1
  power: 2.0
  sr: 16000
  augmentation:
    enabled: true
    max_mask_freq: 15
    max_mask_time: 15
    n_freq_masks: 2
    n_time_masks: 3
    noise_level: 0.01
  audio_augmentation:
    enabled: true
    time_stretch:
      enabled: true
      probability: 0.6
      min_factor: 0.7
      max_factor: 1.3
    pitch_shift:
      enabled: true
      probability: 0.6
      min_steps: -4
      max_steps: 4
    background_noise:
      enabled: true
      probability: 0.6
      min_factor: 0.005
      max_factor: 0.04
  preprocessing_batch_size: 32
  dataset_chunking:
    enabled: true
    chunk_size: 5000
    temp_directory: "./temp_chunks/temp_chunks_AST"

# Fit algorithm parameters
fit:
  compile:
    optimizer: "adamW"
    learning_rate: 0.00001 #0.0003
    loss: "focal_loss"
    metrics: ["accuracy", "Precision", "Recall", "AUC"]
  epochs: 100
  batch_size: 16
  shuffle: true
  validation_split: 0.1
  early_stopping:
    enabled: true
    monitor: "val_loss"
    patience: 10
    min_delta: 0.001
    restore_best_weights: true
  lr_scheduler:
    enabled: true
    monitor: "val_loss"
    factor: 0.5
    patience: 5
    min_lr: 0.00000001

# Training optimizations
training:
  mixed_precision: true
  gradient_accumulation_steps: 2
  gradient_clip_norm: 1.0
  mixup:
    enabled: true
    alpha: 0.3


training:
  load_model: true
# Enhanced transformer model settings
model:
  model_path: model/MAST/mast_model.keras 
  architecture:
    transformer:
      num_heads: 8
      dim_feedforward: 768
      num_encoder_layers: 3
      positional_encoding: true
      patch_size: 4
      attention_dropout: 0.2
      pos_encoding_type: "sinusoidal"
  loss: "focal_loss"
  focal_loss:
    gamma: 2.5
    alpha: 0.5



# MAST specific configuration
mast:
  pretraining:
    enabled: true
    epochs: 10
    batch_size: 32
    learning_rate: 1e-4
    masking:
      probability: 0.15
      mask_length: 8
      mask_time: true
      mask_freq: true
  finetuning:
    enabled: true
    initial_learning_rate: 5e-5
    warmup_epochs: 2
  patch_size: 16

# Dataset generation parameters
dataset:
  split_ratio: [0.7, 0.1, 0.2]
  file_extension: "wav"

# Evaluation parameters
evaluation:
  custom_threshold: 0.5
  metrics: ["accuracy", "precision", "recall", "f1_score", "auc"]

# Directory paths
base_directory: "./dataset"
pickle_directory: "./pickle/pickle_MAST"
model_directory: "./model/MAST"
result_directory: "./result/result_MAST"
result_file: "result_MAST.yaml"

# Logging parameters
logging:
  log_directory: "./logs/log_MAST"
  log_file: "baseline_MAST.log"
  log_level: "DEBUG"
