# Feature extraction parameters
feature:
  n_mels: 64
  frames: 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

# Fit algorithm parameters
fit:
  compile:
    optimizer: "adam"
    loss: "mean_squared_error"
  epochs: 100
  batch_size: 512
  shuffle: True
  validation_split: 0.1
  verbose: 1
  early_stopping: True

# Filter to focus on specific dataset parts
filter:
  enabled: true
  db_level: "0dB"
  machine_type: "fan"
  machine_id: null  # set to specific ID or null for all

# Model architecture parameters
model:
  architecture:
    depth: 3
    width: 64
    bottleneck: 8
    activation: "relu"  # Try "relu", "leaky_relu", "elu"
    dropout: 0.2
    batch_norm: true
    residual: true
  loss: "mse"  # Options: "mse", "ssim", "hybrid"
  hybrid_loss_alpha: 0.5  # Balance between MSE and SSIM when using hybrid loss

# Directory paths
base_directory: "./dataset"
pickle_directory: "./pickle_fnn"
model_directory: "./model_fnn"
result_directory: "./result_fnn"
result_file: "result_fnn.yaml"