# Feature extraction parameters
feature:
  n_mels: 64
  frames: 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

# Transformer model parameters
transformer:
  head_size: 64
  num_heads: 4
  ff_dim: 128
  num_transformer_blocks: 2
  mlp_units: [128, 64]
  dropout: 0.2

# Fit algorithm parameters
fit:
  epochs: 100
  batch_size: 32
  shuffle: True
  validation_split: 0.1
  verbose: 1
  early_stopping: True
  learning_rate: 0.001

# Directory paths
base_directory: "./dataset"
pickle_directory: "./pickle"
model_directory: "./model"
result_directory: "./result"
result_file: "result_transformer.yaml"