perform_tuning: false
force_retrain: true

# Dataset selection parameters
dataset:
  db_levels: ["0dB"]  # List of dB levels to include: ["0dB", "6dB", "min6dB"] for all
  machine_types: ["fan"]  # List of machine types to include: ["fan", "pump", "slider", "valve"] for all

# Feature extraction parameters
feature:
  n_mels: 64
  frames: 5  # Keep at 5 to match previous model for comparison
  n_fft: 1024
  hop_length: 512
  power: 2.0
  use_patches: false  # Change to false - patches are causing worse reconstruction

# Fit algorithm parameters
fit:
  compile:
    optimizer: "adam"
    loss: "hybrid_loss"
  epochs: 150  # Increase from 100 to 150 for better convergence
  batch_size: 256  # Reduced from 512 to 256 for better gradient updates
  shuffle: True
  validation_split: 0.15  # Increased slightly
  verbose: 1
  early_stopping: True
  learning_rate: 0.001
  use_augmentation: true
  augmentation_factor: 3  # Increased from 2 to 3 for more data diversity
  layer_size: 128  # Increased from 64 to 128
  bottleneck_size: 32  # Increased from 8 to 32
  dropout_rate: 0.15  # Slightly reduced
  loss_alpha: 0.3  # Changed to prioritize SSIM more
  depth: 3  # Added depth parameter for the model
  activation: "elu"  # Added activation parameter
  weight_decay: 1e-5  # Added weight decay for regularization

# Directory paths
base_directory: "./dataset"
pickle_directory: "./pickle_fnn"
model_directory: "./model_fnn"
result_directory: "./result_fnn"
result_file: "result_fnn.yaml"