# Feature extraction parameters
feature:
  n_mels: 64
  frames: 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

# Fit algorithm parameters
fit:
  compile:
    optimizer: "adam"
    loss: "mean_squared_error"
  epochs: 100
  batch_size: 512
  shuffle: True
  validation_split: 0.1
  verbose: 1
  early_stopping: True

# Directory paths
base_directory: "./dataset"
pickle_directory: "./pickle_fnn"
model_directory: "./model_fnn"
result_directory: "./result_fnn"
result_file: "result_fnn.yaml"