# Feature extraction parameters
feature:
  n_mels: 64
  frames: 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

# Fit algorithm parameters
fit:
  compile:
    optimizer: "adam"
    loss: "mean_squared_error"
    weighted_metrics: []  # Add this to fix the warning
  epochs: 150
  batch_size: 512
  shuffle: True
  validation_split: 0.1
  verbose: 1
  early_stopping: true
  weight_factor: 1.5  # For non-problematic IDs
  weighted_machine_ids: []  # Will handle id_00 and id_04 explicitly in code
  apply_sample_weights: true  # Enable sample weighting

# Filter to focus on specific dataset parts
filter:
  enabled: false
  db_level: "0dB"
  machine_type: "fan" #...
  machine_id: null  # null means all IDs

# Model architecture parameters
model:
  architecture:
    depth: 4  # Keep original depth
    width: 128  # Keep original width
    bottleneck: 32  # Keep original bottleneck
    activation: "relu"
    dropout: 0.2  # Keep original dropout
    batch_norm: true
    residual: true
  loss: "hybrid"
  hybrid_loss_alpha: 0.4  # Reduced from 0.6 to prioritize SSIM
  margin: 1.0  # Keep original margin value

# Directory paths
base_directory: "./dataset"
pickle_directory: "./pickle_fnn"
model_directory: "./model_fnn"
result_directory: "./result_fnn"
result_file: "result_fnn.yaml"