perform_tuning: false
force_retrain: true

# Dataset selection parameters
dataset:
  db_levels: ["0dB"]  # List of dB levels to include: ["0dB", "6dB", "min6dB"] for all
  machine_types: ["fan"]  # List of machine types to include: ["fan", "pump", "slider", "valve"] for all

# Feature extraction parameters
feature:
  n_mels: 64
  frames: 5  # Keep at 5 to match previous model for comparison
  n_fft: 1024
  hop_length: 512
  power: 2.0
  use_patches: false  # Change to false - patches are causing worse reconstruction

# Fit algorithm parameters
fit:
  compile:
    optimizer: "adam"
    loss: "hybrid_loss"
  epochs: 100
  batch_size: 512
  shuffle: True
  validation_split: 0.15
  verbose: 1
  early_stopping: True
  learning_rate: 0.001
  lr_first_decay_steps: 15
  lr_t_mul: 2.0
  lr_m_mul: 0.85
  lr_min_factor: 0.1
  early_stopping_patience: 10
  early_stopping_min_delta: 0.0005
  use_augmentation: true
  augmentation_factor: 3
  layer_size: 96
  bottleneck_size: 16
  dropout_rate: 0.25
  loss_alpha: 0.5
  depth: 2
  activation: "elu"
  weight_decay: 0.0001
  mixed_precision: true
  cache_dataset: true

# Directory paths
base_directory: "./dataset"
pickle_directory: "./pickle"
model_directory: "./model"
result_directory: "./result"
result_file: "result.yaml"