# Feature extraction parameters
feature:
  n_mels: 64
  frames: 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

# Fit algorithm parameters
fit:
  compile:
    optimizer: "adam"
    loss: "binary_crossentropy"
    metrics: ["accuracy"]
    weighted_metrics: ["accuracy"]
  epochs: 150
  batch_size: 512
  shuffle: True
  validation_split: 0.1
  verbose: 1
  early_stopping: true
  weight_factor: 1.5  # For non-problematic IDs
  weighted_machine_ids: []  # Will handle id_00 and id_04 explicitly in code
  apply_sample_weights: true  # Enable sample weighting

# Filter to focus on specific dataset parts
filter:
  enabled: false
  db_level: "0dB"
  machine_type: "fan"
  machine_id: null  # null means all IDs

# Model architecture parameters
model:
  architecture:
    depth: 4
    width: 128
    bottleneck: 32
    activation: "sigmoid"  # Changed to sigmoid for binary values
    dropout: 0.2
    batch_norm: true
    residual: true
  loss: "binary_crossentropy"

# Directory paths
base_directory: "./dataset"
pickle_directory: "./pickle_fnn"
model_directory: "./model_fnn"
result_directory: "./result_fnn"
result_file: "result_fnn.yaml"